{
  "modified": "2024-06-25T13:39:48Z",
  "published": "2024-06-25T13:39:48Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5682",
  "aliases": [
    "SNYK-PYTHON-PYCRYPTEXE-5295961"
  ],
  "summary": "Malicious code in pycryptexe (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pycryptexe",
        "purl": "pkg:pypi/pycryptexe"
      },
      "versions": [
        "1.0.8",
        "1.0.0",
        "1.0.7",
        "1.0.5",
        "1.0.4",
        "1.0.1",
        "1.0.2",
        "1.0.6",
        "1.1.0",
        "1.0.3",
        "1.0.9",
        "1.1.3",
        "1.1.6",
        "1.1.5",
        "1.1.4"
      ]
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/DataDog/malicious-software-packages-dataset"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYCRYPTEXE-5295961"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04465",
        "import_time": "2024-06-28T02:50:03.39671318Z",
        "modified_time": "2024-06-25T13:39:48Z",
        "sha256": "231f10cb7377f69baaf6f092362108c14d7eecf401938147e3397d5b52751baf",
        "source": "reversing-labs",
        "versions": [
          "1.0.8",
          "1.0.0",
          "1.0.7",
          "1.0.5",
          "1.0.4",
          "1.0.1",
          "1.0.2",
          "1.0.6",
          "1.1.0",
          "1.0.3",
          "1.0.9",
          "1.1.3",
          "1.1.6",
          "1.1.5",
          "1.1.4"
        ]
      }
    ]
  }
}
