{
  "modified": "2024-06-25T13:40:23Z",
  "published": "2024-06-25T13:40:23Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5743",
  "summary": "Malicious code in pymaniac (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pymaniac",
        "purl": "pkg:pypi/pymaniac"
      },
      "versions": [
        "6.0",
        "7.0",
        "8.0",
        "0.1",
        "0.9",
        "0.7",
        "4.0",
        "0.4",
        "3.0",
        "9.1",
        "0.5",
        "2.0",
        "5.0",
        "9.0",
        "0.6",
        "0.2",
        "0.8"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04536",
        "import_time": "2024-06-28T02:50:11.906038243Z",
        "modified_time": "2024-06-25T13:40:23Z",
        "sha256": "931b471ddabbbe71168aba9009c00fc615c2edced14709bf0b7aaaa3f342673c",
        "source": "reversing-labs",
        "versions": [
          "6.0",
          "7.0",
          "8.0",
          "0.1",
          "0.9",
          "0.7",
          "4.0",
          "0.4",
          "3.0",
          "9.1",
          "0.5",
          "2.0",
          "5.0",
          "9.0",
          "0.6",
          "0.2",
          "0.8"
        ]
      }
    ]
  }
}
