{
  "modified": "2024-06-25T13:37:43Z",
  "published": "2024-06-25T13:37:43Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5426",
  "summary": "Malicious code in oauth2gen (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "oauth2gen",
        "purl": "pkg:pypi/oauth2gen"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04208",
        "import_time": "2024-06-28T02:49:33.293915621Z",
        "modified_time": "2024-06-25T13:37:43Z",
        "sha256": "085cfdd5fe85e95ec64d322a6fc16936e134a0c180e36305c57f0801466231d6",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
