{
  "modified": "2024-06-25T13:42:03Z",
  "published": "2024-06-25T13:42:03Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5945",
  "summary": "Malicious code in rhermann-sds (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "rhermann-sds",
        "purl": "pkg:pypi/rhermann-sds"
      },
      "versions": [
        "99.0"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04746",
        "import_time": "2024-06-28T02:50:37.142669631Z",
        "modified_time": "2024-06-25T13:42:03Z",
        "sha256": "8ca24b70ae6292a314a6b7b75b9c3766bc7cc5ea35792b8df7dce163cf25402f",
        "source": "reversing-labs",
        "versions": [
          "99.0"
        ]
      }
    ]
  }
}
