{
  "modified": "2024-06-25T13:41:47Z",
  "published": "2024-06-25T13:41:47Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5911",
  "aliases": [
    "SNYK-PYTHON-REQUESXT-6513210"
  ],
  "summary": "Malicious code in requesxt (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "requesxt",
        "purl": "pkg:pypi/requesxt"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-REQUESXT-6513210"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04712",
        "import_time": "2024-06-28T02:50:32.919545575Z",
        "modified_time": "2024-06-25T13:41:47Z",
        "sha256": "36f527b8b2a7c623ef22ac79249f8bfd627fe0764f365a9df83657b9856aa1a7",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
