{
  "modified": "2024-06-25T13:39:30Z",
  "published": "2024-06-25T13:39:30Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5648",
  "summary": "Malicious code in pycalculate (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pycalculate",
        "purl": "pkg:pypi/pycalculate"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/DataDog/malicious-software-packages-dataset"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04430",
        "import_time": "2024-06-28T02:49:59.269818113Z",
        "modified_time": "2024-06-25T13:39:30Z",
        "sha256": "cf627d7a92b0d87266c54f3f700762b3e0c8cc11d471d777d0232ef5cef87c2b",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
