{
  "modified": "2024-06-25T13:37:24Z",
  "published": "2024-06-25T13:37:24Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5384",
  "summary": "Malicious code in multiconnects (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "multiconnects",
        "purl": "pkg:pypi/multiconnects"
      },
      "versions": [
        "2.34.7",
        "2.34.8",
        "2.34.11",
        "2.34.9",
        "2.34.10"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04166",
        "import_time": "2024-06-28T02:49:28.370883708Z",
        "modified_time": "2024-06-25T13:37:24Z",
        "sha256": "61a7a767264010a51a4a4655e624efdb79261e6360290434cc36ce0fbda32757",
        "source": "reversing-labs",
        "versions": [
          "2.34.7",
          "2.34.8",
          "2.34.11",
          "2.34.9",
          "2.34.10"
        ]
      }
    ]
  }
}
