{
  "modified": "2024-06-25T13:41:26Z",
  "published": "2024-06-25T13:41:26Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5865",
  "aliases": [
    "SNYK-PYTHON-REQEUSTE-6513386"
  ],
  "summary": "Malicious code in reqeuste (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "reqeuste",
        "purl": "pkg:pypi/reqeuste"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-REQEUSTE-6513386"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04666",
        "import_time": "2024-06-28T02:50:27.337383012Z",
        "modified_time": "2024-06-25T13:41:26Z",
        "sha256": "622ced63dd1afd9f162f963d2073e94b6d8300bc64edf4f2902245c2a7ca4e00",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
