{
  "modified": "2024-06-25T13:34:11Z",
  "published": "2024-06-25T13:34:11Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-4987",
  "aliases": [
    "SNYK-PYTHON-COLOUORAMA-6513296"
  ],
  "summary": "Malicious code in colouorama (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "colouorama",
        "purl": "pkg:pypi/colouorama"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-COLOUORAMA-6513296"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-03767",
        "import_time": "2024-06-28T02:48:41.167969412Z",
        "modified_time": "2024-06-25T13:34:11Z",
        "sha256": "98c5434214e1a915236fd3939c0f466ce1d0080eb45d027887bc8df0f86a3610",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
