{
  "modified": "2024-06-25T13:40:19Z",
  "published": "2024-06-25T13:40:19Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5734",
  "aliases": [
    "SNYK-PYTHON-PYLIBHELPER-5932297"
  ],
  "summary": "Malicious code in pylibhelper (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pylibhelper",
        "purl": "pkg:pypi/pylibhelper"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYLIBHELPER-5932297"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04527",
        "import_time": "2024-06-28T02:50:10.787229086Z",
        "modified_time": "2024-06-25T13:40:19Z",
        "sha256": "e724771d4050661d328f80f8c7887bbab98db798b08c386a431116c87b54f8d2",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
