{
  "modified": "2024-06-25T13:38:41Z",
  "published": "2024-06-25T13:38:41Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5546",
  "aliases": [
    "SNYK-PYTHON-PIPSQLPACKAGEV2-5932270"
  ],
  "summary": "Malicious code in pipsqlpackagev2 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pipsqlpackagev2",
        "purl": "pkg:pypi/pipsqlpackagev2"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PIPSQLPACKAGEV2-5932270"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04328",
        "import_time": "2024-06-28T02:49:47.421440384Z",
        "modified_time": "2024-06-25T13:38:41Z",
        "sha256": "8d1f5deb74ecbee7ffca33dd18acbad6a68b12546061f51f3a3a0f0b387bd201",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
