{
  "modified": "2024-06-25T13:32:03Z",
  "published": "2024-06-25T13:32:03Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-4722",
  "summary": "Malicious code in 191239aa (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "191239aa",
        "purl": "pkg:pypi/191239aa"
      },
      "versions": [
        "10.87"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-03502",
        "import_time": "2024-06-28T02:48:11.066709386Z",
        "modified_time": "2024-06-25T13:32:03Z",
        "sha256": "027bd63e571f8a5c79ad89ebba6fb3d4d054e8be5197a600f4f9e02dc6f660a4",
        "source": "reversing-labs",
        "versions": [
          "10.87"
        ]
      }
    ]
  }
}
