{
  "modified": "2024-06-25T13:32:07Z",
  "published": "2024-06-25T13:32:07Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-4730",
  "summary": "Malicious code in adm3 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "adm3",
        "purl": "pkg:pypi/adm3"
      },
      "versions": [
        "1.8.0"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-03510",
        "import_time": "2024-06-28T02:48:11.976336717Z",
        "modified_time": "2024-06-25T13:32:07Z",
        "sha256": "af769f88e433f42170ec8b0c4eac0c0fdc62d4bb4dfdace3bda8e563da5aa38e",
        "source": "reversing-labs",
        "versions": [
          "1.8.0"
        ]
      }
    ]
  }
}
