{
  "modified": "2024-06-25T13:32:33Z",
  "published": "2024-06-25T13:32:33Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-4785",
  "summary": "Malicious code in asynciooo (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "asynciooo",
        "purl": "pkg:pypi/asynciooo"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-03565",
        "import_time": "2024-06-28T02:48:18.176291736Z",
        "modified_time": "2024-06-25T13:32:33Z",
        "sha256": "5bb6e3aac6f3bb488a22f653c9d7ccea85c578c12217c5b045095a87ff4e6553",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
