{
  "modified": "2024-06-25T13:32:19Z",
  "published": "2024-06-25T13:32:19Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-4757",
  "summary": "Malicious code in aiosync (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "aiosync",
        "purl": "pkg:pypi/aiosync"
      },
      "versions": [
        "0.0.5",
        "0.0.1",
        "0.0.3",
        "0.0.8",
        "0.0.7"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-03537",
        "import_time": "2024-06-28T02:48:14.968802462Z",
        "modified_time": "2024-06-25T13:32:19Z",
        "sha256": "51b6ebda6dcc74dcd69c4e648589836dd70821a61290804c7bacb8c67853f4ab",
        "source": "reversing-labs",
        "versions": [
          "0.0.5",
          "0.0.1",
          "0.0.3",
          "0.0.8",
          "0.0.7"
        ]
      }
    ]
  }
}
