{
  "modified": "2024-06-25T13:36:12Z",
  "published": "2024-06-25T13:36:12Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5236",
  "aliases": [
    "SNYK-PYTHON-HTTPXADVANCED3-5292149"
  ],
  "summary": "Malicious code in httpx-advanced3 (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "httpx-advanced3",
        "purl": "pkg:pypi/httpx-advanced3"
      },
      "versions": [
        "0.1.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-HTTPXADVANCED3-5292149"
    },
    {
      "type": "ARTICLE",
      "url": "https://www.fortinet.com/blog/threat-research/supply-chain-attack-via-new-malicious-python-packages"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2024-04018",
        "import_time": "2024-06-28T02:49:10.95738056Z",
        "modified_time": "2024-06-25T13:36:12Z",
        "sha256": "8d12a602f3a1bd7f8f48137ceed0f7cc31dca8e82ee68adf1ae7aea85c39106a",
        "source": "reversing-labs",
        "versions": [
          "0.1.0"
        ]
      }
    ]
  }
}
